meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: shell
    templates:
      - { release: shell, name: shell }
    instances: 1
    persistent_disk: 0
    resource_pool: small_z1
    networks: (( param "please set shell networks" ))
    properties:
      shell:
        users:
          - name: juser
          - name: alice
            shell: /bin/zsh
            ssh_keys:
              - ssh-rsa ABCDEF
          - name: bob
            env: https://github.com/jhunt/env.git
            ssh_keys:
              - ssh-rsa ABCDEF
              - ssh-rsa 123456


networks: (( param "please set networks" ))

properties: {}
