---
meta:
  name:    shell
  release: Shell
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 3.2.0

  bosh-lite:
    target: https://10.58.111.44:25555
    deployment: shell-warden

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  github:
    owner:  cloudfoundry-community
    repo:   shell-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shell-boshrelease/github:private" ))
    access_token: (( vault "secret/pipelines/shell-boshrelease/github:token" ))

  slack:
    webhook: (( vault "secret/pipelines/shell-boshrelease/slack:webhook" ))
    channel: '#botspam'
